funfact_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]
# --> can use this by just changing the main [questionbank.append(Questions(ques["text"],ques["answer"]))]
# else you can use any other online trivia questions like the one below:
question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "Salt is 100% composed of Sodium.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Celebrities",
     "question": "Tupac Shakur died due to complications from being stabbed in 1996.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                                      "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game&#039;s plot.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "The color of the pills in the Matrix were Blue and Yellow.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "hard", "category": "General Knowledge",
                                      "question": "In Scandinavian languages, the letter &Aring; means river.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "Seoul is the capital of North Korea.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Animals",
     "question": "Hyenas are more closely related to cats than to dogs.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In &quot;Undertale&quot;, the main character of the game is Sans.", "correct_answer": "False",
     "incorrect_answers": ["True"]}]
